/*
 * JS for profileScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '13554f0c-4a4c-443d-9eb8-8a11b25342da';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "profileScreen",
    "location": "profileScreen.html"
}, {
    "name": "visitedScreen",
    "location": "visitedScreen.html"
}];

function profileScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'lblFullName': 'profileScreen_lblFullName',
        'lblTitle': 'profileScreen_lblTitle',
        'lblDistrict': 'profileScreen_lblDistrict',
        'lblArea': 'profileScreen_lblArea',
        'lnkPhone': 'profileScreen_lnkPhone',
        'lnkEmail': 'profileScreen_lnkEmail',
        'lblBuilding': 'profileScreen_lblBuilding',
        'imgPicture': 'profileScreen_imgPicture'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["profileScreen_get_profile_onsuccess_mapping_0"] = {
        "homeScreen": "profileScreen",
        "directions": [

        {
            "from_name": "get_profile",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "profileScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['FullName']",
                "target": "$['lblFullName:text']"

            },

            {

                "source": "$['body']['FullName']",
                "target": "$['hdrProfileCaption:text']"

            },

            {

                "source": "$['body']['Title']",
                "target": "$['lblTitle:text']"

            },

            {

                "source": "$['body']['LongDistrict']",
                "target": "$['lblDistrict:text']"

            },

            {

                "source": "$['body']['Area']",
                "target": "$['lblArea:text']"

            },

            {

                "source": "$['body']['PhoneLink']",
                "target": "$['lnkPhone:url']"

            },

            {

                "source": "$['body']['Phone']",
                "target": "$['lnkPhone:text']"

            },

            {

                "source": "$['body']['Email']",
                "target": "$['lnkEmail:text']"

            },

            {

                "source": "$['body']['EmailLink']",
                "target": "$['lnkEmail:url']"

            },

            {

                "source": "$['body']['FullRoom']",
                "target": "$['lblBuilding:text']"

            },

            {

                "source": "$['body']['Image']",
                "target": "$['imgPicture:image']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["profileScreen_get_profile_onbeforesend_mapping_0"] = {
        "homeScreen": "profileScreen",
        "directions": [

        {
            "from_name": "branch",
            "from_type": "LOCAL_STORAGE",

            "to_name": "get_profile",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['branch']"

            }

            ]
        },

        {
            "from_name": "house",
            "from_type": "LOCAL_STORAGE",

            "to_name": "get_profile",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['house']"

            }

            ]
        },

        {
            "from_name": "senate",
            "from_type": "LOCAL_STORAGE",

            "to_name": "get_profile",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['senate']"

            }

            ]
        },

        {
            "from_name": "congress",
            "from_type": "LOCAL_STORAGE",

            "to_name": "get_profile",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['congress']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.get_profile = Apperyio.datasources.get_profile = new Apperyio.DataSource(GetProfileService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["profileScreen_get_profile_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["profileScreen_get_profile_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'profileScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var profileScreen_onLoad = function() {
            profileScreen_elementsExtraJS();

            try {
                get_profile.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            profileScreen_deviceEvents();
            profileScreen_windowEvents();
            profileScreen_elementsEvents();
        };

    // screen window events


    function profileScreen_windowEvents() {

        $('#profileScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function profileScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function profileScreen_elementsExtraJS() {
        // screen (profileScreen) extra code

    };

    // screen elements handler


    function profileScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#profileScreen").on("pagebeforeshow", "#profileScreen", function(event, ui) {
        Apperyio.CurrentScreen = "profileScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    profileScreen_onLoad();
};

$(document).off("pagecreate", "#profileScreen").on("pagecreate", "#profileScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    profileScreen_js();
});