/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '13554f0c-4a4c-443d-9eb8-8a11b25342da';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "profileScreen",
    "location": "profileScreen.html"
}, {
    "name": "visitedScreen",
    "location": "visitedScreen.html"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'btnGetLatLng': 'startScreen_btnGetLatLng',
        'mobilegrid_3': 'startScreen_mobilegrid_3',
        'mobilegridcell_4': 'startScreen_mobilegridcell_4',
        'lblLatitude': 'startScreen_lblLatitude',
        'mobilegridcell_5': 'startScreen_mobilegridcell_5',
        'lblLongitude': 'startScreen_lblLongitude',
        'mobilegrid_11': 'startScreen_mobilegrid_11',
        'mobilegridcell_12': 'startScreen_mobilegridcell_12',
        'txtHouseNo': 'startScreen_txtHouseNo',
        'mobilegridcell_13': 'startScreen_mobilegridcell_13',
        'txtStreet': 'startScreen_txtStreet',
        'mobilegridcell_16': 'startScreen_mobilegridcell_16',
        'txtZip': 'startScreen_txtZip',
        'mobilelist_22': 'startScreen_mobilelist_22',
        'itmMayor': 'startScreen_itmMayor',
        'mobilelistitembutton_24': 'startScreen_mobilelistitembutton_24',
        'itmCongress': 'startScreen_itmCongress',
        'mobilelistitembutton_26': 'startScreen_mobilelistitembutton_26',
        'itmSenator': 'startScreen_itmSenator',
        'mobilelistitembutton_28': 'startScreen_mobilelistitembutton_28',
        'itmHouseRep': 'startScreen_itmHouseRep',
        'mobilelistitembutton_30': 'startScreen_mobilelistitembutton_30',
        'btnViewVisited': 'startScreen_btnViewVisited'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["startScreen_get_location_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {

            "to_name": "get_location",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startScreen_get_location_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "get_location",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['data']['coords']['latitude']",
                "target": "$['lblLatitude:text']"

            },

            {

                "source": "$['data']['coords']['longitude']",
                "target": "$['lblLongitude:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_get_address_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "get_address",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['address']['postalcode']",
                "target": "$['txtZip:text']"

            },

            {

                "source": "$['body']['address']['street']",
                "target": "$['txtStreet:text']"

            },

            {

                "source": "$['body']['address']['streetNumber']",
                "target": "$['txtHouseNo:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_get_address_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "startScreen",
            "from_type": "UI",

            "to_name": "get_address",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "formatted": "true",
                    "username": "terrylp",
                    "style": "full"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['lblLatitude:text']",
                "target": "$['parameters']['lat']"

            },

            {

                "source": "$['lblLongitude:text']",
                "target": "$['parameters']['lng']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_get_electeds_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "get_electeds",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['mayorDistrict']",
                "target": "$['itmMayor:text']"

            },

            {

                "source": "$['body']['congressionalRepDistrict']",
                "target": "$['itmCongress:text']"

            },

            {

                "source": "$['body']['senateRepDistrict']",
                "target": "$['itmSenator:text']"

            },

            {

                "source": "$['body']['houseRepDistrict']",
                "target": "$['itmHouseRep:text']"

            }

            ]
        },

        {
            "from_name": "get_electeds",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "house",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['house']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "get_electeds",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "senate",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['senate']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "get_electeds",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "congress",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['congress']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "get_electeds",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "council",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['council']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_get_electeds_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "startScreen",
            "from_type": "UI",

            "to_name": "get_electeds",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['txtHouseNo:text']",
                "target": "$['parameters']['houseno']"

            },

            {

                "source": "$['txtStreet:text']",
                "target": "$['parameters']['street']"

            },

            {

                "source": "$['txtZip:text']",
                "target": "$['parameters']['zip']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_record_ballot_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": []
    };

    Apperyio.mappings["startScreen_record_ballot_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "congress",
            "from_type": "LOCAL_STORAGE",

            "to_name": "record_ballot",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['cd']"

            }

            ]
        },

        {
            "from_name": "house",
            "from_type": "LOCAL_STORAGE",

            "to_name": "record_ballot",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['hd']"

            }

            ]
        },

        {
            "from_name": "senate",
            "from_type": "LOCAL_STORAGE",

            "to_name": "record_ballot",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['sd']"

            }

            ]
        },

        {
            "from_name": "council",
            "from_type": "LOCAL_STORAGE",

            "to_name": "record_ballot",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['cc']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.get_location = Apperyio.datasources.get_location = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_get_location_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_get_location_onsuccess_mapping_0"]);
            try {
                get_address.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.get_address = Apperyio.datasources.get_address = new Apperyio.DataSource(GetNearestAddress, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_get_address_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_get_address_onsuccess_mapping_0"]);
            try {
                get_electeds.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.get_electeds = Apperyio.datasources.get_electeds = new Apperyio.DataSource(GetElectedsService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_get_electeds_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_get_electeds_onsuccess_mapping_0"]);
            try {
                record_ballot.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.record_ballot = Apperyio.datasources.record_ballot = new Apperyio.DataSource(RecordVisit, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_record_ballot_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_record_ballot_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

        /* mobilelist_22 */

        listView = $("#startScreen_mobilelist_22");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_mobilelist_22 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* itmMayor */

        /* itmCongress */

        /* itmSenator */

        /* itmHouseRep */

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startScreen_mobilecontainer [name="btnGetLatLng"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        get_location.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#startScreen_mobilecontainer [name="btnGetLatLng"]');

        $(document).off("click", '#startScreen_mobilecontainer [name="itmMayor"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["branch"].update("$", "mayor")
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('profileScreen', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilecontainer [name="itmMayor"]');

        $(document).off("click", '#startScreen_mobilecontainer [name="itmCongress"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["branch"].update("$", "congress")
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('profileScreen', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilecontainer [name="itmCongress"]');

        $(document).off("click", '#startScreen_mobilecontainer [name="itmSenator"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["branch"].update("$", "senate")
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('profileScreen', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilecontainer [name="itmSenator"]');

        $(document).off("click", '#startScreen_mobilecontainer [name="itmHouseRep"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["branch"].update("$", "house")
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('profileScreen', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilecontainer [name="itmHouseRep"]');

        $(document).off("click", '#startScreen_mobilecontainer [name="btnViewVisited"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('visitedScreen', {
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilecontainer [name="btnViewVisited"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});